name: Mirror to GitLab

on:
  push:
    branches: ["**"]
    tags: ["**"]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          GITLAB_REPO: ${{ vars.GITLAB_REPO }}
        run: |
          git remote add gitlab "https://andre.burnt:${GITLAB_TOKEN}@gitlab.com/${GITLAB_REPO}.git"
          git push gitlab --all --force
          git push gitlab --tags --force
